// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: account.sql

package sqlc

import (
	"context"
	"time"
)

const createAutor = `-- name: CreateAutor :one
INSERT INTO accounts (
    "owner", 
    "balance",
    "currency", 
    "created_at" 
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, owner, balance, currency, created_at
`

type CreateAutorParams struct {
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAutor(ctx context.Context, arg CreateAutorParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAutor,
		arg.Owner,
		arg.Balance,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
